const express = require("express");
const app = express();
const server = require("http").Server(app);
const io = require("socket.io")(server);
const { v4: uuidV4 } = require("uuid");

app.set("view engine", "ejs");
app.use(express.static("public"));

app.get("/", (req, res) => {
  // dynamic random room generated by uuid
  res.redirect(`/${uuidV4()}`);
});

app.get("/:room", (req, res) => {
  res.render("room", { roomId: req.params.room });
});

// web socket routes
io.on("connection", (socket) => {
  // event from script.js
  socket.on("join-room", (roomId, userId) => {
    socket.join(roomId);
    // emitting an user-connected event for script.js
    socket.to(roomId).emit("user-connected", userId);
  });
});

server.listen(3000);
